env:
  browser: true
  es2021: true
plugins:
  - react
  - '@typescript-eslint'
  - prettier
extends:
  - eslint:recommended
  - plugin:react/recommended
  - plugin:@typescript-eslint/recommended
overrides: []
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  ecmaFeatures:
    jsx: true
  sourceType: module
rules:
  semi: [2, never]
settings:
  react:
    version: 'detect'
