repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black
        verbose: true
  - repo: https://github.com/PyCQA/flake8
    rev: 5.0.4
    hooks:
      - id: flake8
        args: [--max-line-length=100]
        verbose: true
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0-alpha.4
    hooks:
      - id: prettier
        verbose: true
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.26.0
    hooks:
      - id: eslint
        files: \.[jt]sx?$ # *.js, *.jsx, *.ts and *.tsx
        types: [file]
        verbose: true
  # Crappy way to run pytest. I don't think I am supposed to do this.
  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: bash -c "source ./backend/venv/bin/activate && cd backend && PYTHONPATH=. pytest tests"
        language: system
        pass_filenames: false
        always_run: true
        verbose: true
  # Crappy way to run jest. I don't think I am supposed to do this.
  - repo: local
    hooks:
      - id: jest
        name: jest
        entry: bash -c "cd frontend && yarn test"
        language: system
        pass_filenames: false
        always_run: true
        verbose: true
